[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Jure Slak <jure.slak@gmail.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main2020"
path = "src/2020/main.rs"
